steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$GCP-flaskhelloworldapp1-347923/$GCP-flaskhelloworldapp1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$GCP-flaskhelloworldapp1-347923/$GCP-flaskhelloworldapp1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$GCP-flaskhelloworldapp1', '--gcr.io/flaskhelloworldapp1-347923/flaskhelloworldapp1@sha256:780b0952eaff04a665c0cf5326cf0ba32b4829d8cde8f1b7ef2bbfa22a5b90cd', 'gcr.io/$GCP-flaskhelloworldapp1-347923/$GCP-flaskhelloworldapp1', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/$GCP-flaskhelloworldapp1-347923/$GCP-flaskhelloworldapp1